 # Numpy 2 복습

In [151]:
import numpy as np

- ### sum 및 axis

In [152]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
a.sum()                     # a의 element를 다 더한 값

78

In [154]:
a.sum(axis=0)                # 각 열들의 합

array([15, 18, 21, 24])

In [155]:
a.sum(axis=1)                 # 각 행들의 합

array([10, 26, 42])

In [156]:
sum(a[0])                     # a의 0번째 인덱스인 [1, 2, 3, 4]의 값을 다 더함

10

- ### sorting(정렬)

In [157]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [158]:
np.sort(b)                 # 각 행들의 element를 오름차순으로 정렬
                           # axis=1이 디폴트 값            

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [159]:
b[:,::-1]                   # 각 행들의 element를 내림차순으로 변경

array([[ 7,  5,  3,  4],
       [ 9, 11, 12,  1],
       [14,  1,  5,  2]])

In [160]:
# 내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42, 38, 12, 25])
np.sort(c)[::-1] 

array([42, 38, 25, 12])

In [161]:
np.argsort(c)                   # 인덱스의 순서로 돌려줌

array([2, 3, 1, 0], dtype=int64)

In [162]:
indices = np.argsort(c)         # 인덱스의 순서로 돌려놨던 것의 
c[indices]                      # 인덱스를 다시 이용해서 값을 돌려줌

array([12, 25, 38, 42])

In [163]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- ### Transpose

In [164]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [165]:
b.T                           # 행과 열을 바꿔줌

array([[ 4,  1,  2],
       [ 3, 12,  5],
       [ 5, 11,  1],
       [ 7,  9, 14]])

- ### concatenate , vstack, hstack

In [166]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [167]:
np.vstack((a,b))                         # vstack은 행으로 붙이는 느낌

array([[1, 2],
       [3, 4],
       [5, 6]])

In [168]:
np.hstack((a,b.T))                       # hstack은 열로 붙이는 느낌
                                         # 그러므로 모양이 맞아야됨
                                         # 이 상황은 Transpose로 모양을 
                                         # 맞게해준다음 더해줌

array([[1, 2, 5],
       [3, 4, 6]])

- ### Array operation

In [169]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [170]:
a+a , a-a, a*a, a/a

(array([[2, 4],
        [6, 8]]),
 array([[0, 0],
        [0, 0]]),
 array([[ 1,  4],
        [ 9, 16]]),
 array([[1., 1.],
        [1., 1.]]))

- ### Broadcasting

In [171]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [172]:
a + 3                      # 각 element에 3을 더해줌

array([[4, 5],
       [6, 7]])

- ### dot product

In [173]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [174]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [175]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
np.dot(a,b)                            # a의 열 인덱스와
                                       # b의 행 인덱스가 같아야 가능.

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [177]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

- ### Comparison

In [178]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [180]:
np.any(a>5), np.all(a>5)           # any는 부분적인게 있냐
                                   # all은 모든게 그렇냐

(True, False)

- ### Logical operation

In [181]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [183]:
c = np.logical_or(a < 3, a>7)
c

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- ### argmax, argmin

In [189]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [190]:
np.argmin(a) , np.argmax(a)                  # 최솟값, 최댓값의 인덱스를 알려줌

(0, 11)

- ### Boolean & Fancy index

In [191]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
a[a > 5]

array([6, 7, 8, 9])

In [192]:
a[np.logical_or(a < 3, a > 7)]

array([0, 1, 2, 8, 9])

IndexError: index 3 is out of bounds for axis 0 with size 3