# 1. Numpy
- ### 넘파이 어레이 인덱싱에서 행이 우선

In [16]:
import numpy as np
import pandas as pd

# reshape 하기   
- ### size가 같으면 reshape 가능
- #### ㄴ사이즈가 12인 a를 reshape하려면 a.reshape(3,4)해도 되지만
- ####       a.reshape(3,-1) 하면 -1이 알아서 그 자리의 값을 매겨줌
- #### ㄴ reshape는 1차원 -> 2차원 , 2차원 -> 3차원 으로 만들어줌

In [12]:
# Matrix(2차원)
a = np.array([[1,2,4],[4,3,9],[3,7,8],[1,4,5]])
a

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8],
       [1, 4, 5]])

In [18]:
a.size

12

In [26]:
a.reshape(3,-1)

array([[1, 2, 4, 4],
       [3, 9, 3, 7],
       [8, 1, 4, 5]])

- ### 2차원을 3차원으로 만들어줌

In [47]:
b = np.arange(1,28).reshape(3,3,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# 2차원 array를 1차원 array로 만들어주는 법
### ㄴflatten() 사용하기

In [27]:
a = np.array([[1,2,4],[4,3,9],[3,7,8],[1,4,5]])
a

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8],
       [1, 4, 5]])

In [28]:
a.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8, 1, 4, 5])

# 인덱싱과 슬라이싱 하기

In [48]:
a = np.array([[1,2,4],[4,3,9],[3,7,8],[1,4,5]])
a

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8],
       [1, 4, 5]])

In [53]:
a[0]

array([1, 2, 4])

In [54]:
a[0][1]

2

# 넘파이 array를 리스트로 바꾸는법
- ### .tolist()

In [57]:
a = np.arange(1, 4.1, 0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [58]:
a.tolist()

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

### ones, zeros

In [67]:
np.ones(shape=(10,))          # 열의 값이 빈칸일때 10은 1의 개수를 의미

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.ones(shape=(2,4))          # 열의 값이 있을때는 2 는 행의 갯수
                              # 4는 열의 갯수를 의미

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
np.zeros(5)                     # ones에서와 같음

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros(shape=(2,4))           # ones에서와 같음

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# identity , eye
- #### ㄴ대각선에 1을 놔줌
- #### 정방형은 identity
- #### 직사각형은 eye
- #### ㄴ직사각형은 np.eye(3,5 k=1)처럼 k값을 줌으로써-
- #### -대각선에 들어가는 1의 시작위치를 정할 수 있음

In [85]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.eye(3, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# 데이터 분포에 따른 random sampling

In [88]:
np.random.seed(2021)

In [89]:
np.random.random(4)      # 0-1사이의 아무 값 4개를 뽑음

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

In [98]:
np.random.seed(2021)          
np.random.normal(0,1,4)    #np.random.normal(평균,표준편차,n(개수))

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081])

In [99]:
np.random.seed(2021)        # 정규분포
np.random.randn(4)          # np.random.normal(0,1,n(개수))

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081])

In [107]:
np.random.randint(1,7,10)       #np.randint(시작,끝 (전까지),갯수)

array([4, 2, 5, 3, 4, 2, 3, 6, 3, 6])