In [2]:
import numpy as np

### 4. Operation

In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [4]:
a.sum()

78

In [5]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
a.sum(axis=1)

array([10, 26, 42])

In [7]:
np.sum(a[0])

10

- sorting

In [14]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [15]:
np.sort(b)       # axis=1 , ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [16]:
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [17]:
b.sort()


In [18]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [19]:
np.sort(b,axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [29]:
c = np.array([42,38, 12,25])
np.sort(c)[::-1]                   #내림차순 정리

array([42, 38, 25, 12])

In [30]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [32]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [33]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathmatical funtions

In [34]:
def sigmoid (x):
    return 1./(1+np.exp(-x))

In [37]:
xs = np.array([-10,0,10])              # 기억하길 바람.
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

-  Transpose

In [38]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [40]:
b.T                            #행과 열 바꿔치기

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [42]:
a = np.array([[1, 2], [3, 4]])
a                                    #shape (2 x 2)

array([[1, 2],
       [3, 4]])

In [48]:
b = np.array([[5, 6]])                #shape (1 X 2)

In [49]:
b   

array([[5, 6]])

In [50]:
np.vstack((a,b))                          #shape(3 X 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [58]:
a

array([[1, 2],
       [3, 4]])

In [53]:
a + a

array([[2, 4],
       [6, 8]])

In [54]:
a-a

array([[0, 0],
       [0, 0]])

In [55]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [56]:
a / a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [59]:
a + 3

array([[4, 5],
       [6, 7]])

- dot product

In [62]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [65]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [69]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5.Comparison

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [72]:
np.any(a>5),np.all(a>5)

(True, False)

- Logical operation

In [76]:
b = np.logical_and(a > 3, a < 7 )
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [111]:
np.logical_or(a < 3, a > 7)

ValueError: invalid number of arguments

- argmax , argmin

In [78]:
np.argmax(a),np.argmin(a)

(9, 0)

### 6.Boolean & Fancy index

In [85]:
a[a > 5]

array([6, 7, 8, 9])

In [81]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [80]:
a[b]

array([4, 5, 6])

In [84]:
a[np.logical_or(a < 3 , a > 7)]

array([0, 1, 2, 8, 9])

In [86]:
a[[3,5,7]]

array([3, 5, 7])

In [87]:
a[[3,5,7,3]]

array([3, 5, 7, 3])

### 7. 기술 통계

In [90]:
a = np.random.randn(10)
a

array([-0.58194789, -0.93712801,  0.35052616,  0.81976542,  0.0506462 ,
        0.50628219, -0.48313788,  0.07701064, -0.2769647 , -0.69937004])

In [93]:
#평균(Mean)
a.mean() , np.mean(a)                           # 평균 구하는 법

(-0.1174317926484291, -0.1174317926484291)

In [98]:
#표준 편차(Standard deviation)
a.std(), np.std(a)                               # 표준 편차(Standard deviation)

(0.5420259560752285, 0.5420259560752285)

In [99]:
#최댓값 최솟값
a.max(), a.min()      

(0.8197654162824756, -0.9371280125876441)

In [101]:
np.max(a),np.min(a)

(0.8197654162824756, -0.9371280125876441)

In [103]:
#4분위수
np.percentile(a,100) , np.percentile(a,0)


(0.8197654162824756, -0.9371280125876441)

In [104]:
np.percentile(a, 25) , np.percentile(a, 75)

(-0.5572453884404981, 0.28214727716102866)

In [106]:
np.percentile(a, 50) , np.median(a)

(-0.11315925311783119, -0.11315925311783118)