In [1]:
import numpy as np

### 4. Operation

In [2]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [3]:
a.sum()

78

In [4]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [5]:
a.sum(axis=1)

array([10, 26, 42])

In [6]:
np.sum(a[0])

10

- sorting

In [7]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [8]:
np.sort(b)       # axis=1 , ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [9]:
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [10]:
b.sort()


In [11]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [12]:
np.sort(b,axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [60]:
c = np.array([42,38, 12,25])
c

array([42, 38, 12, 25])

In [61]:
c = np.array([42,38, 12,25])
np.sort(c)[::-1]                   #내림차순 정리

array([42, 38, 25, 12])

In [14]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [15]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [16]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathmatical funtions

In [17]:
def sigmoid (x):
    return 1./(1+np.exp(-x))

In [18]:
xs = np.array([-10,0,10])              # 기억하길 바람.
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

-  Transpose

In [19]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [20]:
b.T                            #행과 열 바꿔치기

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [21]:
a = np.array([[1, 2], [3, 4]])
a                                    #shape (2 x 2)

array([[1, 2],
       [3, 4]])

In [22]:
b = np.array([[5, 6]])                #shape (1 X 2)

In [23]:
b   

array([[5, 6]])

In [24]:
np.vstack((a,b))                          #shape(3 X 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
a + a

array([[2, 4],
       [6, 8]])

In [28]:
a-a

array([[0, 0],
       [0, 0]])

In [29]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [30]:
a / a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [31]:
a + 3

array([[4, 5],
       [6, 7]])

- dot product

In [32]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [33]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [36]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5.Comparison

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [39]:
np.any(a>5),np.all(a>5)

(True, False)

- Logical operation

In [40]:
b = np.logical_and(a > 3, a < 7 )
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [41]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax , argmin

In [42]:
np.argmax(a),np.argmin(a)

(9, 0)

### 6.Boolean & Fancy index

In [43]:
a[a > 5]

array([6, 7, 8, 9])

In [44]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [45]:
a[b]

array([4, 5, 6])

In [46]:
a[np.logical_or(a < 3 , a > 7)]

array([0, 1, 2, 8, 9])

In [47]:
a[[3,5,7]]

array([3, 5, 7])

In [48]:
a[[3,5,7,3]]

array([3, 5, 7, 3])

### 7. 기술 통계

In [49]:
a = np.random.randn(10)
a

array([-0.49588179,  0.94627162,  0.95896396,  0.67604708,  1.47902933,
        0.74794347, -0.14565346, -0.86390635, -0.77709506,  1.51155248])

In [50]:
#평균(Mean)
a.mean() , np.mean(a)                           # 평균 구하는 법

(0.40372712714043535, 0.40372712714043535)

In [51]:
#표준 편차(Standard deviation)
a.std(), np.std(a)                               # 표준 편차(Standard deviation)

(0.8538845495782382, 0.8538845495782382)

In [52]:
#최댓값 최솟값
a.max(), a.min()      

(1.5115524773833906, -0.8639063514123043)

In [53]:
np.max(a),np.min(a)

(1.5115524773833906, -0.8639063514123043)

In [54]:
#4분위수
np.percentile(a,100) , np.percentile(a,0)


(1.5115524773833906, -0.8639063514123043)

In [55]:
np.percentile(a, 25) , np.percentile(a, 75)

(-0.40832470605561655, 0.9557908756533489)

In [56]:
np.percentile(a, 50) , np.median(a)

(0.7119952729229486, 0.7119952729229486)