In [2]:
import numpy as np

### 1번 문제

In [5]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [423]:
a = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2번 문제

In [7]:
m=np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [424]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9], 
              [10, 11, 12, 13, 14]])

In [425]:
#1. 
m[1][2]

7

In [426]:
#2
m[2][4]

14

In [427]:
#3
m[1,1:3].tolist()

[6, 7]

In [11]:
#4
b = m[1:,2]
b

array([ 7, 12])

In [429]:
#5
k = m[:2,3:]
k.tolist()

[[3, 4], [8, 9]]

### 3번 문제

In [16]:
m=np.arange(0,15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [430]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9], 
              [10, 11, 12, 13, 14]])         
f = m.flatten()
f


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [431]:
#1.
f[np.logical_and(f % 3 == 0,f != 0) ].tolist()

[3, 6, 9, 12]

In [432]:
#2.
f[f % 4 == 1].tolist()

[1, 5, 9, 13]

In [433]:
#3.
f[np.logical_and(f % 3 == 0,f % 4 == 1)].tolist()

[9]

### 4번 문제

In [24]:
np.eye(5,5,-1,int)*3+np.eye(5,5,0,int)*2+np.eye(5,5,1,int)*1


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [436]:
b = np.identity(5)*2
c = np.eye(N=5,M=5,k =1)
a = np.eye(5, 5, k=-1)*3
d = a+b+c
d.tolist()

[[2.0, 1.0, 0.0, 0.0, 0.0],
 [3.0, 2.0, 1.0, 0.0, 0.0],
 [0.0, 3.0, 2.0, 1.0, 0.0],
 [0.0, 0.0, 3.0, 2.0, 1.0],
 [0.0, 0.0, 0.0, 3.0, 2.0]]

### 5번문제

In [437]:
import numpy as np

In [27]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [29]:
#5-1
m.max()

9.9724

In [30]:
#5-2
m[0].sum(), m[1].sum() ,m[2].sum() ,m[3].sum() ,m[4].sum()


(29.163700000000002, 25.3385, 38.072199999999995, 23.6387, 32.0221)

In [31]:
m.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [32]:
np.sum(m, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [33]:
#5-3
m[0].max(), m[1].max(), m[2].max(), m[3].max(), m[4].max()

(9.9724, 7.8431, 9.6384, 5.743, 8.231)

In [34]:
m.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [36]:
#5-4
m[:,0].mean(), m[:,1].mean(), m[:,2].mean(), m[:,3].mean(), m[:,4].mean(),m[:,5].mean()

(5.810740000000001,
 5.90066,
 3.7154,
 5.3664000000000005,
 6.024380000000001,
 2.82946)

In [35]:
m.mean(axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [443]:
#5-5
h[:,0].min() , h[:,1].min() , h[:,2].min(), h[:,3].min(), h[:,4].min() ,h[:,5].min()

(1.7483, 0.2771, 1.7066, 3.5266, 0.3022, 4.2804)

In [38]:
m.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### 6번문제

In [37]:
import numpy as np

In [40]:
score = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71], 
              [ 81,   59,   90,  100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [43]:
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [44]:
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [46]:
score[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [54]:
score[:,np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [445]:
a = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71], 
              [ 81,   59,   90,  100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [446]:
a[0] =[46,  99, 100,  71]

In [447]:
a[1] = [  1,    2,    3,    4]

In [451]:
a

array([[ 46,  99, 100,  71],
       [  1,   2,   3,   4],
       [ 81,  59,  90, 100]])

In [448]:
a.T

array([[ 46,   1,  81],
       [ 99,   2,  59],
       [100,   3,  90],
       [ 71,   4, 100]])

# 7번 문제

In [59]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
np.mean(dice)

3.7

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,7,100)
a.mean()

3.42

In [62]:
# dice array에서의 고유값
np.unique(dice)          

array([1, 2, 3, 4, 5, 6])

In [63]:
# dice array에서 고유값 및 그 갯수
np.unique(dice,return_counts= True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [66]:
unique, counts = np.unique(dice, return_counts= True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

# 8번 문제

In [72]:
# 5개만 먼저 테스트
np.random.seed(2021)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [88]:
#250
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_list=[]
for i in range(250):
    price = price + np.round(price * rate[i])
    price_list.append(price)

price_array = np.array(price_list,dtype = np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [92]:
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250, dtype= np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]


array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])