In [422]:
import numpy as np

### 1번 문제

In [423]:
a = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2번 문제

In [424]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9], 
              [10, 11, 12, 13, 14]])

In [425]:
#1. 
m[1][2]

7

In [426]:
#2
m[2][4]

14

In [427]:
#3
m[1,1:3].tolist()

[6, 7]

In [428]:
#4
b = m[1:,[2]]
b.reshape(-1,2)
b.flatten().tolist()

[7, 12]

In [429]:
#5
k = m[:2,3:]
k.tolist()

[[3, 4], [8, 9]]

### 3번 문제

In [430]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9], 
              [10, 11, 12, 13, 14]])         
f = m.flatten()
f


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [431]:
#1.
f[np.logical_and(f % 3 == 0,f != 0) ].tolist()

[3, 6, 9, 12]

In [432]:
#2.
f[f % 4 == 1].tolist()

[1, 5, 9, 13]

In [433]:
#3.
f[np.logical_and(f % 3 == 0,f % 4 == 1)].tolist()

[9]

### 4번 문제

In [434]:
b = np.identity(5)*2
b

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [435]:
c = np.eye(N=5,M=5,k =1)
c

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [436]:
b = np.identity(5)*2
c = np.eye(N=5,M=5,k =1)
a = np.eye(5, 5, k=-1)*3
d = a+b+c
d.tolist()

[[2.0, 1.0, 0.0, 0.0, 0.0],
 [3.0, 2.0, 1.0, 0.0, 0.0],
 [0.0, 3.0, 2.0, 1.0, 0.0],
 [0.0, 0.0, 3.0, 2.0, 1.0],
 [0.0, 0.0, 0.0, 3.0, 2.0]]

### 5번문제

In [437]:
import numpy as np

In [438]:
c = np.random.uniform(0,10,30)
d = c.reshape(5,6)
h = np.round(d,4)
h

array([[6.4248, 7.9809, 5.9298, 4.6986, 8.0464, 4.2804],
       [7.0237, 6.599 , 8.2517, 3.5266, 1.3255, 8.2201],
       [7.2788, 6.7324, 1.7066, 9.6207, 7.7282, 7.7785],
       [7.2297, 1.1457, 5.9827, 4.6453, 8.6811, 9.5484],
       [1.7483, 0.2771, 4.8006, 6.7309, 0.3022, 8.9585]])

In [439]:
#5-1
h.max()

9.6207

In [440]:
#5-2
h[0].sum(), h[1].sum() ,h[2].sum() ,h[3].sum() ,h[4].sum()


(37.3609, 34.946600000000004, 40.8452, 37.2329, 22.817600000000002)

In [441]:
#5-3
h[0].max(), h[1].max(), h[2].max(), h[3].max(), h[4].max()

(8.0464, 8.2517, 9.6207, 9.5484, 8.9585)

In [442]:
#5-4
h[:,0].mean(), h[:,1].mean(), h[:,2].mean(), h[:,3].mean(), h[:,4].mean(),h[:,5].mean()

(5.94106, 4.547020000000001, 5.33428, 5.8444199999999995, 5.21668, 7.75718)

In [443]:
#5-5
h[:,0].min() , h[:,1].min() , h[:,2].min(), h[:,3].min(), h[:,4].min() ,h[:,5].min()

(1.7483, 0.2771, 1.7066, 3.5266, 0.3022, 4.2804)

### 6번문제

In [444]:
import numpy as np

In [445]:
a = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71], 
              [ 81,   59,   90,  100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [446]:
a[0] =[46,  99, 100,  71]

In [447]:
a[1] = [  1,    2,    3,    4]

In [451]:
a

array([[ 46,  99, 100,  71],
       [  1,   2,   3,   4],
       [ 81,  59,  90, 100]])

In [448]:
a.T

array([[ 46,   1,  81],
       [ 99,   2,  59],
       [100,   3,  90],
       [ 71,   4, 100]])

# 7번 문제

In [449]:
import random as rd

In [457]:
a = np.random.randint(1,7,100)
a.mean()

3.45